# Generated by Django 5.2.8 on 2026-03-18 08:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_is_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='default_tasks',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='ChallengeDailyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField()),
                ('task_items', models.JSONField(default=list)),
                ('media_urls', models.JSONField(default=list)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='challenges.challengeparticipant')),
            ],
            options={
                'unique_together': {('participant', 'day_number')},
            },
        ),
    ]
