# Generated by Django 5.2.8 on 2026-04-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_add_payment_certificate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
