# Generated by Django 5.2.8 on 2026-04-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_add_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='unit',
            field=models.CharField(choices=[('kcal', 'kcal'), ('reps', 'reps'), ('sets', 'sets'), ('days', 'days'), ('minutes', 'minutes'), ('km', 'km'), ('grams', 'grams'), ('ml', 'ml'), ('calories_burned', 'Calories Burned')], max_length=20),
        ),
    ]
