# Generated by Django 5.2.8 on 2026-04-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_extend_unit_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='max_participants',
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='prize_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='prize_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='prize_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='unit',
            field=models.CharField(choices=[('kcal', 'kcal'), ('reps', 'reps'), ('days', 'days')], max_length=10),
        ),
    ]
