from django.core.management.base import BaseCommand
from workouts.models import Exercise, Gym


class Command(BaseCommand):
    help = 'Seeds the database with 100+ exercises covering all categories, muscle groups, and difficulty levels'

    def handle(self, *args, **kwargs):
        self.stdout.write('Seeding exercises...')
        
        exercises_data = [
            # STRENGTH - CHEST - FREE_WEIGHTS
            {
                'name': 'Barbell Bench Press',
                'description': 'Classic compound chest exercise using a barbell',
                'category': 'STRENGTH',
                'muscle_group': 'CHEST',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Lie on bench with feet flat\n2. Grip bar slightly wider than shoulders\n3. Lower bar to chest\n4. Press back up',
                'calories_per_minute': 6.0,
            },
            {
                'name': 'Dumbbell Bench Press',
                'description': 'Chest press using dumbbells for greater range of motion',
                'category': 'STRENGTH',
                'muscle_group': 'CHEST',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'BEGINNER',
                'instructions': '1. Lie on bench with dumbbells\n2. Press dumbbells up\n3. Lower with control\n4. Keep elbows at 45 degrees',
                'calories_per_minute': 5.5,
            },
            {
                'name': 'Incline Dumbbell Press',
                'description': 'Upper chest focused dumbbell press',
                'category': 'STRENGTH',
                'muscle_group': 'CHEST',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Set bench to 30-45 degrees\n2. Press dumbbells up\n3. Lower to chest level\n4. Maintain control',
                'calories_per_minute': 5.5,
            },
            {
                'name': 'Decline Barbell Press',
                'description': 'Lower chest focused barbell press',
                'category': 'STRENGTH',
                'muscle_group': 'CHEST',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'ADVANCED',
                'instructions': '1. Lie on decline bench\n2. Lower bar to lower chest\n3. Press up explosively\n4. Control the descent',
                'calories_per_minute': 6.5,
            },
            
            # STRENGTH - CHEST - MACHINES
            {
                'name': 'Chest Press Machine',
                'description': 'Machine-based chest press for controlled movement',
                'category': 'STRENGTH',
                'muscle_group': 'CHEST',
                'equipment': 'MACHINES',
                'difficulty': 'BEGINNER',
                'instructions': '1. Adjust seat height\n2. Grip handles\n3. Press forward\n4. Return slowly',
                'calories_per_minute': 5.0,
            },
            {
                'name': 'Cable Chest Fly',
                'description': 'Isolation exercise for chest using cables',
                'category': 'STRENGTH',
                'muscle_group': 'CHEST',
                'equipment': 'MACHINES',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Set cables to chest height\n2. Bring handles together\n3. Squeeze chest\n4. Return with control',
                'calories_per_minute': 4.5,
            },
            
            # STRENGTH - BACK - FREE_WEIGHTS
            {
                'name': 'Barbell Deadlift',
                'description': 'Compound exercise for entire posterior chain',
                'category': 'STRENGTH',
                'muscle_group': 'BACK',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'ADVANCED',
                'instructions': '1. Stand with feet hip-width\n2. Grip bar outside legs\n3. Lift by extending hips and knees\n4. Keep back straight',
                'calories_per_minute': 8.0,
            },
            {
                'name': 'Barbell Row',
                'description': 'Compound back exercise for thickness',
                'category': 'STRENGTH',
                'muscle_group': 'BACK',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Bend at hips\n2. Pull bar to lower chest\n3. Squeeze shoulder blades\n4. Lower with control',
                'calories_per_minute': 6.5,
            },
            {
                'name': 'Dumbbell Row',
                'description': 'Single-arm back exercise',
                'category': 'STRENGTH',
                'muscle_group': 'BACK',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'BEGINNER',
                'instructions': '1. Support on bench\n2. Pull dumbbell to hip\n3. Squeeze back\n4. Lower slowly',
                'calories_per_minute': 5.5,
            },
            {
                'name': 'T-Bar Row',
                'description': 'Thick back builder using T-bar',
                'category': 'STRENGTH',
                'muscle_group': 'BACK',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Straddle bar\n2. Pull to chest\n3. Keep back straight\n4. Control descent',
                'calories_per_minute': 6.0,
            },
            
            # STRENGTH - BACK - MACHINES
            {
                'name': 'Lat Pulldown',
                'description': 'Machine exercise for lat width',
                'category': 'STRENGTH',
                'muscle_group': 'BACK',
                'equipment': 'MACHINES',
                'difficulty': 'BEGINNER',
                'instructions': '1. Sit with thighs secured\n2. Pull bar to upper chest\n3. Squeeze lats\n4. Return slowly',
                'calories_per_minute': 5.0,
            },
            {
                'name': 'Seated Cable Row',
                'description': 'Cable row for back thickness',
                'category': 'STRENGTH',
                'muscle_group': 'BACK',
                'equipment': 'MACHINES',
                'difficulty': 'BEGINNER',
                'instructions': '1. Sit with feet on platform\n2. Pull handle to abdomen\n3. Squeeze back\n4. Extend arms',
                'calories_per_minute': 5.0,
            },
            {
                'name': 'Machine Back Extension',
                'description': 'Lower back strengthening machine',
                'category': 'STRENGTH',
                'muscle_group': 'BACK',
                'equipment': 'MACHINES',
                'difficulty': 'BEGINNER',
                'instructions': '1. Position hips on pad\n2. Extend back\n3. Control movement\n4. Return to start',
                'calories_per_minute': 4.0,
            },
            
            # STRENGTH - LEGS - FREE_WEIGHTS
            {
                'name': 'Barbell Squat',
                'description': 'King of leg exercises',
                'category': 'STRENGTH',
                'muscle_group': 'LEGS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Bar on upper back\n2. Squat down\n3. Keep chest up\n4. Drive through heels',
                'calories_per_minute': 7.0,
            },
            {
                'name': 'Front Squat',
                'description': 'Quad-focused squat variation',
                'category': 'STRENGTH',
                'muscle_group': 'LEGS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'ADVANCED',
                'instructions': '1. Bar on front delts\n2. Squat keeping torso upright\n3. Drive up\n4. Maintain balance',
                'calories_per_minute': 7.5,
            },
            {
                'name': 'Romanian Deadlift',
                'description': 'Hamstring and glute focused deadlift',
                'category': 'STRENGTH',
                'muscle_group': 'LEGS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Hold bar at thighs\n2. Hinge at hips\n3. Feel hamstring stretch\n4. Return to standing',
                'calories_per_minute': 6.5,
            },
            {
                'name': 'Walking Lunges',
                'description': 'Dynamic single-leg exercise',
                'category': 'STRENGTH',
                'muscle_group': 'LEGS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'BEGINNER',
                'instructions': '1. Step forward\n2. Lower back knee\n3. Push through front heel\n4. Alternate legs',
                'calories_per_minute': 6.0,
            },
            {
                'name': 'Bulgarian Split Squat',
                'description': 'Single-leg squat variation',
                'category': 'STRENGTH',
                'muscle_group': 'LEGS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Rear foot elevated\n2. Lower into lunge\n3. Drive through front leg\n4. Maintain balance',
                'calories_per_minute': 6.5,
            },
            
            # STRENGTH - LEGS - MACHINES
            {
                'name': 'Leg Press',
                'description': 'Machine-based leg exercise',
                'category': 'STRENGTH',
                'muscle_group': 'LEGS',
                'equipment': 'MACHINES',
                'difficulty': 'BEGINNER',
                'instructions': '1. Feet on platform\n2. Push platform away\n3. Lower with control\n4. Keep back against pad',
                'calories_per_minute': 5.5,
            },
            {
                'name': 'Leg Extension',
                'description': 'Quad isolation exercise',
                'category': 'STRENGTH',
                'muscle_group': 'LEGS',
                'equipment': 'MACHINES',
                'difficulty': 'BEGINNER',
                'instructions': '1. Sit in machine\n2. Extend legs\n3. Squeeze quads\n4. Lower slowly',
                'calories_per_minute': 4.0,
            },
            {
                'name': 'Leg Curl',
                'description': 'Hamstring isolation exercise',
                'category': 'STRENGTH',
                'muscle_group': 'LEGS',
                'equipment': 'MACHINES',
                'difficulty': 'BEGINNER',
                'instructions': '1. Lie face down\n2. Curl heels to glutes\n3. Squeeze hamstrings\n4. Lower slowly',
                'calories_per_minute': 4.0,
            },
            {
                'name': 'Calf Raise Machine',
                'description': 'Calf isolation on machine',
                'category': 'STRENGTH',
                'muscle_group': 'LEGS',
                'equipment': 'MACHINES',
                'difficulty': 'BEGINNER',
                'instructions': '1. Shoulders under pads\n2. Raise heels high\n3. Squeeze calves\n4. Lower for stretch',
                'calories_per_minute': 3.5,
            },
            
            # STRENGTH - ARMS - FREE_WEIGHTS
            {
                'name': 'Barbell Curl',
                'description': 'Classic bicep builder',
                'category': 'STRENGTH',
                'muscle_group': 'ARMS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'BEGINNER',
                'instructions': '1. Hold bar at thighs\n2. Curl to shoulders\n3. Squeeze biceps\n4. Lower slowly',
                'calories_per_minute': 4.0,
            },
            {
                'name': 'Dumbbell Curl',
                'description': 'Bicep exercise with dumbbells',
                'category': 'STRENGTH',
                'muscle_group': 'ARMS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'BEGINNER',
                'instructions': '1. Arms at sides\n2. Curl dumbbells up\n3. Rotate wrists\n4. Lower with control',
                'calories_per_minute': 4.0,
            },
            {
                'name': 'Hammer Curl',
                'description': 'Neutral grip bicep curl',
                'category': 'STRENGTH',
                'muscle_group': 'ARMS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'BEGINNER',
                'instructions': '1. Hold dumbbells neutral grip\n2. Curl up\n3. Keep elbows still\n4. Lower slowly',
                'calories_per_minute': 4.0,
            },
            {
                'name': 'Skull Crushers',
                'description': 'Tricep extension exercise',
                'category': 'STRENGTH',
                'muscle_group': 'ARMS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Lie on bench\n2. Lower bar to forehead\n3. Extend arms\n4. Keep elbows in',
                'calories_per_minute': 4.5,
            },
            {
                'name': 'Close-Grip Bench Press',
                'description': 'Tricep-focused bench press',
                'category': 'STRENGTH',
                'muscle_group': 'ARMS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Narrow grip on bar\n2. Lower to chest\n3. Press up\n4. Keep elbows tucked',
                'calories_per_minute': 5.5,
            },
            
            # STRENGTH - ARMS - MACHINES
            {
                'name': 'Cable Tricep Pushdown',
                'description': 'Tricep isolation using cable',
                'category': 'STRENGTH',
                'muscle_group': 'ARMS',
                'equipment': 'MACHINES',
                'difficulty': 'BEGINNER',
                'instructions': '1. Grip bar overhead\n2. Push down\n3. Extend arms fully\n4. Return slowly',
                'calories_per_minute': 3.5,
            },
            {
                'name': 'Cable Bicep Curl',
                'description': 'Constant tension bicep curl',
                'category': 'STRENGTH',
                'muscle_group': 'ARMS',
                'equipment': 'MACHINES',
                'difficulty': 'BEGINNER',
                'instructions': '1. Grip cable bar\n2. Curl up\n3. Squeeze biceps\n4. Lower with control',
                'calories_per_minute': 3.5,
            },
            {
                'name': 'Preacher Curl Machine',
                'description': 'Isolated bicep curl on machine',
                'category': 'STRENGTH',
                'muscle_group': 'ARMS',
                'equipment': 'MACHINES',
                'difficulty': 'BEGINNER',
                'instructions': '1. Arms on pad\n2. Curl handles up\n3. Squeeze at top\n4. Lower slowly',
                'calories_per_minute': 3.5,
            },
            
            # STRENGTH - SHOULDERS - FREE_WEIGHTS
            {
                'name': 'Overhead Press',
                'description': 'Compound shoulder exercise',
                'category': 'STRENGTH',
                'muscle_group': 'SHOULDERS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Bar at shoulders\n2. Press overhead\n3. Lock out arms\n4. Lower with control',
                'calories_per_minute': 6.0,
            },
            {
                'name': 'Dumbbell Shoulder Press',
                'description': 'Shoulder press with dumbbells',
                'category': 'STRENGTH',
                'muscle_group': 'SHOULDERS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'BEGINNER',
                'instructions': '1. Dumbbells at shoulders\n2. Press up\n3. Bring together at top\n4. Lower slowly',
                'calories_per_minute': 5.5,
            },
            {
                'name': 'Lateral Raise',
                'description': 'Side delt isolation',
                'category': 'STRENGTH',
                'muscle_group': 'SHOULDERS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'BEGINNER',
                'instructions': '1. Dumbbells at sides\n2. Raise to shoulder height\n3. Lead with elbows\n4. Lower slowly',
                'calories_per_minute': 3.5,
            },
            {
                'name': 'Front Raise',
                'description': 'Front delt isolation',
                'category': 'STRENGTH',
                'muscle_group': 'SHOULDERS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'BEGINNER',
                'instructions': '1. Dumbbells at thighs\n2. Raise to shoulder height\n3. Keep arms straight\n4. Lower slowly',
                'calories_per_minute': 3.5,
            },
            {
                'name': 'Rear Delt Fly',
                'description': 'Rear deltoid isolation',
                'category': 'STRENGTH',
                'muscle_group': 'SHOULDERS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Bend at hips\n2. Raise dumbbells to sides\n3. Squeeze rear delts\n4. Lower slowly',
                'calories_per_minute': 4.0,
            },
            
            # STRENGTH - SHOULDERS - MACHINES
            {
                'name': 'Shoulder Press Machine',
                'description': 'Machine-based shoulder press',
                'category': 'STRENGTH',
                'muscle_group': 'SHOULDERS',
                'equipment': 'MACHINES',
                'difficulty': 'BEGINNER',
                'instructions': '1. Adjust seat\n2. Press handles up\n3. Extend fully\n4. Lower with control',
                'calories_per_minute': 5.0,
            },
            {
                'name': 'Cable Lateral Raise',
                'description': 'Side delt isolation with cable',
                'category': 'STRENGTH',
                'muscle_group': 'SHOULDERS',
                'equipment': 'MACHINES',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Cable at side\n2. Raise across body\n3. Lead with elbow\n4. Lower slowly',
                'calories_per_minute': 3.5,
            },
            
            # STRENGTH - CORE - FREE_WEIGHTS
            {
                'name': 'Weighted Crunch',
                'description': 'Abdominal crunch with weight',
                'category': 'STRENGTH',
                'muscle_group': 'CORE',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Hold weight on chest\n2. Crunch up\n3. Squeeze abs\n4. Lower slowly',
                'calories_per_minute': 4.5,
            },
            {
                'name': 'Russian Twist with Weight',
                'description': 'Rotational core exercise with weight',
                'category': 'STRENGTH',
                'muscle_group': 'CORE',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Sit with weight\n2. Rotate side to side\n3. Touch ground each side\n4. Keep core tight',
                'calories_per_minute': 5.0,
            },
            {
                'name': 'Dumbbell Side Bend',
                'description': 'Oblique exercise with dumbbell',
                'category': 'STRENGTH',
                'muscle_group': 'CORE',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'BEGINNER',
                'instructions': '1. Hold dumbbell at side\n2. Bend to side\n3. Return to center\n4. Alternate sides',
                'calories_per_minute': 3.5,
            },
            
            # STRENGTH - CORE - MACHINES
            {
                'name': 'Cable Crunch',
                'description': 'Ab crunch using cable machine',
                'category': 'STRENGTH',
                'muscle_group': 'CORE',
                'equipment': 'MACHINES',
                'difficulty': 'BEGINNER',
                'instructions': '1. Kneel with rope overhead\n2. Crunch down\n3. Squeeze abs\n4. Return slowly',
                'calories_per_minute': 4.0,
            },
            {
                'name': 'Ab Wheel Rollout',
                'description': 'Advanced core exercise with wheel',
                'category': 'STRENGTH',
                'muscle_group': 'CORE',
                'equipment': 'MACHINES',
                'difficulty': 'ADVANCED',
                'instructions': '1. Kneel with wheel\n2. Roll forward\n3. Maintain tension\n4. Roll back',
                'calories_per_minute': 6.0,
            },
            
            # STRENGTH - FULL_BODY - FREE_WEIGHTS
            {
                'name': 'Clean and Press',
                'description': 'Olympic lift variation',
                'category': 'STRENGTH',
                'muscle_group': 'FULL_BODY',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'ADVANCED',
                'instructions': '1. Clean bar to shoulders\n2. Press overhead\n3. Lower to shoulders\n4. Return to ground',
                'calories_per_minute': 9.0,
            },
            {
                'name': 'Thruster',
                'description': 'Squat to press combination',
                'category': 'STRENGTH',
                'muscle_group': 'FULL_BODY',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Front squat down\n2. Drive up\n3. Press overhead\n4. Lower to shoulders',
                'calories_per_minute': 8.5,
            },
            {
                'name': 'Kettlebell Swing',
                'description': 'Explosive hip hinge movement',
                'category': 'STRENGTH',
                'muscle_group': 'FULL_BODY',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Hinge at hips\n2. Swing kettlebell up\n3. Drive with hips\n4. Control descent',
                'calories_per_minute': 10.0,
            },
            {
                'name': 'Turkish Get-Up',
                'description': 'Complex full-body movement',
                'category': 'STRENGTH',
                'muscle_group': 'FULL_BODY',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'ADVANCED',
                'instructions': '1. Lie with weight overhead\n2. Stand up\n3. Maintain weight overhead\n4. Reverse to lying',
                'calories_per_minute': 7.0,
            },
            
            # CARDIO - FULL_BODY - CARDIO_EQUIPMENT
            {
                'name': 'Treadmill Running',
                'description': 'Running on treadmill',
                'category': 'CARDIO',
                'muscle_group': 'FULL_BODY',
                'equipment': 'CARDIO_EQUIPMENT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Set desired speed\n2. Maintain steady pace\n3. Land midfoot\n4. Breathe rhythmically',
                'calories_per_minute': 10.0,
            },
            {
                'name': 'Treadmill Incline Walk',
                'description': 'Walking on incline',
                'category': 'CARDIO',
                'muscle_group': 'FULL_BODY',
                'equipment': 'CARDIO_EQUIPMENT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Set incline 10-15%\n2. Walk at moderate pace\n3. Maintain posture\n4. Swing arms naturally',
                'calories_per_minute': 7.0,
            },
            {
                'name': 'Stationary Bike',
                'description': 'Cycling on stationary bike',
                'category': 'CARDIO',
                'muscle_group': 'LEGS',
                'equipment': 'CARDIO_EQUIPMENT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Adjust seat height\n2. Pedal at steady pace\n3. Maintain resistance\n4. Keep core engaged',
                'calories_per_minute': 8.0,
            },
            {
                'name': 'Rowing Machine',
                'description': 'Full-body cardio on rower',
                'category': 'CARDIO',
                'muscle_group': 'FULL_BODY',
                'equipment': 'CARDIO_EQUIPMENT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Secure feet\n2. Pull handle to chest\n3. Drive with legs\n4. Return with control',
                'calories_per_minute': 11.0,
            },
            {
                'name': 'Elliptical Trainer',
                'description': 'Low-impact cardio machine',
                'category': 'CARDIO',
                'muscle_group': 'FULL_BODY',
                'equipment': 'CARDIO_EQUIPMENT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Step on pedals\n2. Move in elliptical motion\n3. Use handles\n4. Maintain rhythm',
                'calories_per_minute': 9.0,
            },
            {
                'name': 'Stair Climber',
                'description': 'Stair climbing machine',
                'category': 'CARDIO',
                'muscle_group': 'LEGS',
                'equipment': 'CARDIO_EQUIPMENT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Step on pedals\n2. Climb at steady pace\n3. Use light hand support\n4. Keep posture upright',
                'calories_per_minute': 9.5,
            },
            {
                'name': 'Assault Bike',
                'description': 'High-intensity air bike',
                'category': 'CARDIO',
                'muscle_group': 'FULL_BODY',
                'equipment': 'CARDIO_EQUIPMENT',
                'difficulty': 'ADVANCED',
                'instructions': '1. Pedal and push handles\n2. Go all out\n3. Maintain intensity\n4. Breathe hard',
                'calories_per_minute': 15.0,
            },
            {
                'name': 'Ski Erg',
                'description': 'Skiing motion cardio machine',
                'category': 'CARDIO',
                'muscle_group': 'FULL_BODY',
                'equipment': 'CARDIO_EQUIPMENT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Pull handles down\n2. Engage core\n3. Drive with arms\n4. Return smoothly',
                'calories_per_minute': 12.0,
            },
            
            # BODYWEIGHT - CHEST
            {
                'name': 'Push-ups',
                'description': 'Classic bodyweight chest exercise',
                'category': 'BODYWEIGHT',
                'muscle_group': 'CHEST',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Plank position\n2. Lower chest to ground\n3. Push back up\n4. Keep core tight',
                'calories_per_minute': 7.0,
            },
            {
                'name': 'Diamond Push-ups',
                'description': 'Tricep-focused push-up variation',
                'category': 'BODYWEIGHT',
                'muscle_group': 'CHEST',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Hands form diamond\n2. Lower down\n3. Push up\n4. Keep elbows in',
                'calories_per_minute': 7.5,
            },
            {
                'name': 'Decline Push-ups',
                'description': 'Feet elevated push-ups',
                'category': 'BODYWEIGHT',
                'muscle_group': 'CHEST',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Feet on bench\n2. Lower chest down\n3. Push up\n4. Maintain form',
                'calories_per_minute': 8.0,
            },
            {
                'name': 'Plyometric Push-ups',
                'description': 'Explosive push-up variation',
                'category': 'BODYWEIGHT',
                'muscle_group': 'CHEST',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'ADVANCED',
                'instructions': '1. Lower down\n2. Push up explosively\n3. Hands leave ground\n4. Land softly',
                'calories_per_minute': 9.0,
            },
            
            # BODYWEIGHT - BACK
            {
                'name': 'Pull-ups',
                'description': 'Classic bodyweight back exercise',
                'category': 'BODYWEIGHT',
                'muscle_group': 'BACK',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'ADVANCED',
                'instructions': '1. Hang from bar\n2. Pull chin over bar\n3. Lower with control\n4. Full extension',
                'calories_per_minute': 8.0,
            },
            {
                'name': 'Chin-ups',
                'description': 'Underhand grip pull-up',
                'category': 'BODYWEIGHT',
                'muscle_group': 'BACK',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Underhand grip\n2. Pull up\n3. Chin over bar\n4. Lower slowly',
                'calories_per_minute': 7.5,
            },
            {
                'name': 'Inverted Row',
                'description': 'Horizontal bodyweight row',
                'category': 'BODYWEIGHT',
                'muscle_group': 'BACK',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Hang under bar\n2. Pull chest to bar\n3. Squeeze back\n4. Lower down',
                'calories_per_minute': 6.0,
            },
            {
                'name': 'Superman Hold',
                'description': 'Lower back isometric hold',
                'category': 'BODYWEIGHT',
                'muscle_group': 'BACK',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Lie face down\n2. Lift arms and legs\n3. Hold position\n4. Lower down',
                'calories_per_minute': 3.0,
            },
            
            # BODYWEIGHT - LEGS
            {
                'name': 'Bodyweight Squat',
                'description': 'Basic squat without weight',
                'category': 'BODYWEIGHT',
                'muscle_group': 'LEGS',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Feet shoulder-width\n2. Squat down\n3. Keep chest up\n4. Stand up',
                'calories_per_minute': 6.0,
            },
            {
                'name': 'Jump Squat',
                'description': 'Explosive squat variation',
                'category': 'BODYWEIGHT',
                'muscle_group': 'LEGS',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Squat down\n2. Jump up explosively\n3. Land softly\n4. Repeat',
                'calories_per_minute': 10.0,
            },
            {
                'name': 'Pistol Squat',
                'description': 'Single-leg squat',
                'category': 'BODYWEIGHT',
                'muscle_group': 'LEGS',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'ADVANCED',
                'instructions': '1. Stand on one leg\n2. Squat down\n3. Other leg extended\n4. Stand up',
                'calories_per_minute': 7.0,
            },
            {
                'name': 'Glute Bridge',
                'description': 'Hip thrust movement',
                'category': 'BODYWEIGHT',
                'muscle_group': 'LEGS',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Lie on back\n2. Lift hips up\n3. Squeeze glutes\n4. Lower down',
                'calories_per_minute': 4.0,
            },
            {
                'name': 'Single-Leg Glute Bridge',
                'description': 'One-legged hip thrust',
                'category': 'BODYWEIGHT',
                'muscle_group': 'LEGS',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Lie on back\n2. One leg extended\n3. Lift hips\n4. Squeeze glutes',
                'calories_per_minute': 5.0,
            },
            
            # BODYWEIGHT - CORE
            {
                'name': 'Plank',
                'description': 'Isometric core hold',
                'category': 'BODYWEIGHT',
                'muscle_group': 'CORE',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Forearm plank\n2. Body straight\n3. Hold position\n4. Breathe steadily',
                'calories_per_minute': 3.0,
            },
            {
                'name': 'Side Plank',
                'description': 'Lateral core hold',
                'category': 'BODYWEIGHT',
                'muscle_group': 'CORE',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Side forearm plank\n2. Body straight\n3. Hold position\n4. Switch sides',
                'calories_per_minute': 3.5,
            },
            {
                'name': 'Bicycle Crunches',
                'description': 'Dynamic ab exercise',
                'category': 'BODYWEIGHT',
                'muscle_group': 'CORE',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Lie on back\n2. Alternate elbow to knee\n3. Twist torso\n4. Keep moving',
                'calories_per_minute': 5.0,
            },
            {
                'name': 'Leg Raises',
                'description': 'Lower ab exercise',
                'category': 'BODYWEIGHT',
                'muscle_group': 'CORE',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Lie on back\n2. Raise legs up\n3. Lower slowly\n4. Keep back flat',
                'calories_per_minute': 4.5,
            },
            {
                'name': 'Hanging Leg Raise',
                'description': 'Advanced ab exercise',
                'category': 'BODYWEIGHT',
                'muscle_group': 'CORE',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'ADVANCED',
                'instructions': '1. Hang from bar\n2. Raise legs to 90 degrees\n3. Lower with control\n4. No swinging',
                'calories_per_minute': 6.0,
            },
            {
                'name': 'Mountain Climbers',
                'description': 'Dynamic core and cardio',
                'category': 'BODYWEIGHT',
                'muscle_group': 'CORE',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Plank position\n2. Drive knees to chest\n3. Alternate quickly\n4. Keep hips down',
                'calories_per_minute': 8.0,
            },
            {
                'name': 'V-Ups',
                'description': 'Advanced ab crunch',
                'category': 'BODYWEIGHT',
                'muscle_group': 'CORE',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'ADVANCED',
                'instructions': '1. Lie flat\n2. Raise arms and legs\n3. Touch toes\n4. Lower down',
                'calories_per_minute': 6.5,
            },
            
            # BODYWEIGHT - ARMS
            {
                'name': 'Tricep Dips',
                'description': 'Bodyweight tricep exercise',
                'category': 'BODYWEIGHT',
                'muscle_group': 'ARMS',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Hands on bench\n2. Lower body down\n3. Push back up\n4. Keep elbows in',
                'calories_per_minute': 5.0,
            },
            {
                'name': 'Bench Dips',
                'description': 'Tricep dips on bench',
                'category': 'BODYWEIGHT',
                'muscle_group': 'ARMS',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Hands on bench behind\n2. Lower down\n3. Push up\n4. Feet on ground',
                'calories_per_minute': 4.5,
            },
            
            # BODYWEIGHT - SHOULDERS
            {
                'name': 'Pike Push-ups',
                'description': 'Shoulder-focused push-up',
                'category': 'BODYWEIGHT',
                'muscle_group': 'SHOULDERS',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Downward dog position\n2. Lower head to ground\n3. Push back up\n4. Keep hips high',
                'calories_per_minute': 6.0,
            },
            {
                'name': 'Handstand Push-ups',
                'description': 'Advanced shoulder exercise',
                'category': 'BODYWEIGHT',
                'muscle_group': 'SHOULDERS',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'ADVANCED',
                'instructions': '1. Handstand against wall\n2. Lower head to ground\n3. Push back up\n4. Maintain balance',
                'calories_per_minute': 8.0,
            },
            
            # BODYWEIGHT - FULL_BODY
            {
                'name': 'Burpees',
                'description': 'Full-body explosive exercise',
                'category': 'BODYWEIGHT',
                'muscle_group': 'FULL_BODY',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Squat down\n2. Kick feet back\n3. Push-up\n4. Jump up',
                'calories_per_minute': 10.0,
            },
            {
                'name': 'Jumping Jacks',
                'description': 'Basic cardio exercise',
                'category': 'BODYWEIGHT',
                'muscle_group': 'FULL_BODY',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Feet together\n2. Jump feet apart\n3. Raise arms\n4. Return to start',
                'calories_per_minute': 8.0,
            },
            {
                'name': 'High Knees',
                'description': 'Running in place with high knees',
                'category': 'BODYWEIGHT',
                'muscle_group': 'FULL_BODY',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Run in place\n2. Drive knees high\n3. Pump arms\n4. Maintain pace',
                'calories_per_minute': 9.0,
            },
            {
                'name': 'Box Jumps',
                'description': 'Explosive jump onto box',
                'category': 'BODYWEIGHT',
                'muscle_group': 'FULL_BODY',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Stand before box\n2. Jump onto box\n3. Land softly\n4. Step down',
                'calories_per_minute': 11.0,
            },
            {
                'name': 'Bear Crawl',
                'description': 'Quadrupedal movement',
                'category': 'BODYWEIGHT',
                'muscle_group': 'FULL_BODY',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Hands and feet on ground\n2. Crawl forward\n3. Keep hips low\n4. Maintain rhythm',
                'calories_per_minute': 7.0,
            },
            
            # CARDIO - BODYWEIGHT
            {
                'name': 'Jump Rope',
                'description': 'Skipping rope cardio',
                'category': 'CARDIO',
                'muscle_group': 'FULL_BODY',
                'equipment': 'RESISTANCE_BANDS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Hold rope handles\n2. Swing overhead\n3. Jump as rope passes\n4. Land on balls of feet',
                'calories_per_minute': 12.0,
            },
            {
                'name': 'Shadow Boxing',
                'description': 'Boxing movements without opponent',
                'category': 'CARDIO',
                'muscle_group': 'FULL_BODY',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Boxing stance\n2. Throw punches\n3. Move feet\n4. Maintain guard',
                'calories_per_minute': 8.0,
            },
            {
                'name': 'Sprints',
                'description': 'Maximum effort running',
                'category': 'CARDIO',
                'muscle_group': 'FULL_BODY',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Sprint at max effort\n2. Drive knees\n3. Pump arms\n4. Maintain form',
                'calories_per_minute': 15.0,
            },
            # Additional exercises to reach 100+
            {
                'name': 'Leg Press',
                'description': 'Machine-based leg exercise',
                'category': 'STRENGTH',
                'muscle_group': 'LEGS',
                'equipment': 'MACHINES',
                'difficulty': 'BEGINNER',
                'instructions': '1. Feet on platform\n2. Push platform away\n3. Lower with control\n4. Keep back against pad',
                'calories_per_minute': 5.5,
            },
            {
                'name': 'Push-ups',
                'description': 'Classic bodyweight chest exercise',
                'category': 'BODYWEIGHT',
                'muscle_group': 'CHEST',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Plank position\n2. Lower chest to ground\n3. Push back up\n4. Keep core tight',
                'calories_per_minute': 7.0,
            },
            {
                'name': 'Pull-ups',
                'description': 'Classic bodyweight back exercise',
                'category': 'BODYWEIGHT',
                'muscle_group': 'BACK',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'ADVANCED',
                'instructions': '1. Hang from bar\n2. Pull chin over bar\n3. Lower with control\n4. Full extension',
                'calories_per_minute': 8.0,
            },
            {
                'name': 'Plank',
                'description': 'Isometric core hold',
                'category': 'BODYWEIGHT',
                'muscle_group': 'CORE',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Forearm plank\n2. Body straight\n3. Hold position\n4. Breathe steadily',
                'calories_per_minute': 3.0,
            },
            {
                'name': 'Burpees',
                'description': 'Full-body explosive exercise',
                'category': 'BODYWEIGHT',
                'muscle_group': 'FULL_BODY',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Squat down\n2. Kick feet back\n3. Push-up\n4. Jump up',
                'calories_per_minute': 10.0,
            },
            {
                'name': 'Jumping Jacks',
                'description': 'Basic cardio exercise',
                'category': 'BODYWEIGHT',
                'muscle_group': 'FULL_BODY',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Feet together\n2. Jump feet apart\n3. Raise arms\n4. Return to start',
                'calories_per_minute': 8.0,
            },
            {
                'name': 'Mountain Climbers',
                'description': 'Dynamic core and cardio',
                'category': 'BODYWEIGHT',
                'muscle_group': 'CORE',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Plank position\n2. Drive knees to chest\n3. Alternate quickly\n4. Keep hips down',
                'calories_per_minute': 8.0,
            },
            {
                'name': 'Tricep Dips',
                'description': 'Bodyweight tricep exercise',
                'category': 'BODYWEIGHT',
                'muscle_group': 'ARMS',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Hands on bench\n2. Lower body down\n3. Push back up\n4. Keep elbows in',
                'calories_per_minute': 5.0,
            },
            {
                'name': 'Dumbbell Fly',
                'description': 'Chest isolation with dumbbells',
                'category': 'STRENGTH',
                'muscle_group': 'CHEST',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Lie on bench\n2. Lower dumbbells to sides\n3. Bring together above chest\n4. Slight bend in elbows',
                'calories_per_minute': 4.5,
            },
            {
                'name': 'Concentration Curl',
                'description': 'Isolated bicep curl',
                'category': 'STRENGTH',
                'muscle_group': 'ARMS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'BEGINNER',
                'instructions': '1. Sit with elbow on thigh\n2. Curl dumbbell up\n3. Squeeze bicep\n4. Lower slowly',
                'calories_per_minute': 3.5,
            },
            {
                'name': 'Arnold Press',
                'description': 'Shoulder press with rotation',
                'category': 'STRENGTH',
                'muscle_group': 'SHOULDERS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Start with palms facing you\n2. Press up while rotating\n3. End with palms forward\n4. Reverse motion',
                'calories_per_minute': 5.5,
            },
            {
                'name': 'Face Pulls',
                'description': 'Rear delt and upper back exercise',
                'category': 'STRENGTH',
                'muscle_group': 'SHOULDERS',
                'equipment': 'MACHINES',
                'difficulty': 'BEGINNER',
                'instructions': '1. Pull rope to face\n2. Separate handles\n3. Squeeze rear delts\n4. Return slowly',
                'calories_per_minute': 3.5,
            },
            {
                'name': 'Shrugs',
                'description': 'Trap isolation exercise',
                'category': 'STRENGTH',
                'muscle_group': 'BACK',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'BEGINNER',
                'instructions': '1. Hold dumbbells at sides\n2. Shrug shoulders up\n3. Hold briefly\n4. Lower slowly',
                'calories_per_minute': 3.0,
            },
            {
                'name': 'Good Mornings',
                'description': 'Hip hinge exercise for hamstrings',
                'category': 'STRENGTH',
                'muscle_group': 'LEGS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Bar on upper back\n2. Hinge at hips\n3. Feel hamstring stretch\n4. Return to standing',
                'calories_per_minute': 5.0,
            },
            {
                'name': 'Hack Squat',
                'description': 'Machine squat variation',
                'category': 'STRENGTH',
                'muscle_group': 'LEGS',
                'equipment': 'MACHINES',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Back against pad\n2. Squat down\n3. Push through heels\n4. Extend legs',
                'calories_per_minute': 6.0,
            },
            {
                'name': 'Farmer Walk',
                'description': 'Loaded carry exercise',
                'category': 'STRENGTH',
                'muscle_group': 'FULL_BODY',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'BEGINNER',
                'instructions': '1. Hold heavy weights\n2. Walk forward\n3. Keep posture upright\n4. Maintain grip',
                'calories_per_minute': 7.0,
            },
            # Additional exercises to ensure 100+ total
            {
                'name': 'Goblet Squat',
                'description': 'Squat holding weight at chest',
                'category': 'STRENGTH',
                'muscle_group': 'LEGS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'BEGINNER',
                'instructions': '1. Hold dumbbell at chest\n2. Squat down\n3. Keep chest up\n4. Drive through heels',
                'calories_per_minute': 6.0,
            },
            {
                'name': 'Sumo Deadlift',
                'description': 'Wide stance deadlift',
                'category': 'STRENGTH',
                'muscle_group': 'LEGS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Wide stance\n2. Grip bar inside legs\n3. Lift by extending hips\n4. Keep back straight',
                'calories_per_minute': 7.5,
            },
            {
                'name': 'Reverse Fly',
                'description': 'Rear delt isolation with dumbbells',
                'category': 'STRENGTH',
                'muscle_group': 'SHOULDERS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'BEGINNER',
                'instructions': '1. Bend at hips\n2. Raise dumbbells to sides\n3. Squeeze rear delts\n4. Lower slowly',
                'calories_per_minute': 3.5,
            },
            {
                'name': 'Upright Row',
                'description': 'Shoulder and trap exercise',
                'category': 'STRENGTH',
                'muscle_group': 'SHOULDERS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Hold bar at thighs\n2. Pull up to chin\n3. Elbows high\n4. Lower slowly',
                'calories_per_minute': 4.5,
            },
            {
                'name': 'Zottman Curl',
                'description': 'Bicep curl with rotation',
                'category': 'STRENGTH',
                'muscle_group': 'ARMS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Curl dumbbells up\n2. Rotate at top\n3. Lower with palms down\n4. Rotate back',
                'calories_per_minute': 4.0,
            },
            {
                'name': 'Overhead Tricep Extension',
                'description': 'Tricep isolation overhead',
                'category': 'STRENGTH',
                'muscle_group': 'ARMS',
                'equipment': 'FREE_WEIGHTS',
                'difficulty': 'BEGINNER',
                'instructions': '1. Hold dumbbell overhead\n2. Lower behind head\n3. Extend arms\n4. Keep elbows in',
                'calories_per_minute': 3.5,
            },
            {
                'name': 'Battle Ropes',
                'description': 'High-intensity rope exercise',
                'category': 'CARDIO',
                'muscle_group': 'FULL_BODY',
                'equipment': 'RESISTANCE_BANDS',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Hold rope ends\n2. Create waves\n3. Maintain intensity\n4. Keep core tight',
                'calories_per_minute': 12.0,
            },
            {
                'name': 'Sled Push',
                'description': 'Pushing weighted sled',
                'category': 'STRENGTH',
                'muscle_group': 'FULL_BODY',
                'equipment': 'MACHINES',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Hands on sled\n2. Push forward\n3. Drive with legs\n4. Maintain posture',
                'calories_per_minute': 11.0,
            },
            {
                'name': 'Sled Pull',
                'description': 'Pulling weighted sled',
                'category': 'STRENGTH',
                'muscle_group': 'FULL_BODY',
                'equipment': 'MACHINES',
                'difficulty': 'INTERMEDIATE',
                'instructions': '1. Attach rope to sled\n2. Pull backward\n3. Use full body\n4. Maintain balance',
                'calories_per_minute': 10.0,
            },
            {
                'name': 'Wall Sit',
                'description': 'Isometric leg exercise',
                'category': 'BODYWEIGHT',
                'muscle_group': 'LEGS',
                'equipment': 'BODYWEIGHT',
                'difficulty': 'BEGINNER',
                'instructions': '1. Back against wall\n2. Slide down to 90 degrees\n3. Hold position\n4. Keep core tight',
                'calories_per_minute': 4.0,
            },
        ]
        
        created_count = 0
        for exercise_data in exercises_data:
            exercise, created = Exercise.objects.get_or_create(
                name=exercise_data['name'],
                defaults=exercise_data
            )
            if created:
                created_count += 1
                self.stdout.write(f'  Created: {exercise.name}')
        
        self.stdout.write(self.style.SUCCESS(f'Successfully created {created_count} exercises'))
        self.stdout.write(self.style.SUCCESS(f'Total exercises in database: {Exercise.objects.count()}'))
        
        # Seed some gyms
        self.stdout.write('Seeding gyms...')
        
        gyms_data = [
            {
                'name': 'FitZone Gym',
                'location': 'Downtown',
                'address': '123 Main Street, City Center',
                'rating': 4.5,
                'phone': '+1234567890',
            },
            {
                'name': 'PowerHouse Fitness',
                'location': 'North District',
                'address': '456 Oak Avenue, North Side',
                'rating': 4.8,
                'phone': '+1234567891',
            },
            {
                'name': 'Elite Training Center',
                'location': 'East Side',
                'address': '789 Elm Road, East District',
                'rating': 4.3,
                'phone': '+1234567892',
            },
            {
                'name': '24/7 Fitness Hub',
                'location': 'West End',
                'address': '321 Pine Street, West Quarter',
                'rating': 4.6,
                'phone': '+1234567893',
            },
        ]
        
        gym_count = 0
        for gym_data in gyms_data:
            gym, created = Gym.objects.get_or_create(
                name=gym_data['name'],
                defaults=gym_data
            )
            if created:
                gym_count += 1
                self.stdout.write(f'  Created: {gym.name}')
        
        self.stdout.write(self.style.SUCCESS(f'Successfully created {gym_count} gyms'))
        self.stdout.write(self.style.SUCCESS('Database seeding completed!'))
