# Generated by Django 5.2.8 on 2026-03-04 17:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('protein_per_100g', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fats_per_100g', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fiber_per_100g', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sugar_per_100g', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_custom', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'food_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HydrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(default='ml', max_length=10)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydration_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hydration_logs',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('meal', 'Meal'), ('snack', 'Snack'), ('drink', 'Drink')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(max_length=20)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=7)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=6)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_logs', to='nutrition.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intake_logs',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.DecimalField(decimal_places=2, default=2000, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('daily_protein', models.DecimalField(decimal_places=2, default=150, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('daily_carbs', models.DecimalField(decimal_places=2, default=200, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('daily_fats', models.DecimalField(decimal_places=2, default=65, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('daily_water', models.DecimalField(decimal_places=2, default=2000, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nutrition_goals',
            },
        ),
        migrations.CreateModel(
            name='NutritionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_date', models.DateField()),
                ('total_calories', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total_protein', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_carbs', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_fats', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_water', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('calories_adherence', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('protein_adherence', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('carbs_adherence', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fats_adherence', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('water_adherence', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nutrition_progress',
                'ordering': ['-progress_date'],
            },
        ),
        migrations.CreateModel(
            name='QuickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequent_meals', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quick_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quick_logs',
            },
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['name'], name='food_items_name_7242ab_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['is_custom', 'created_by'], name='food_items_is_cust_4da792_idx'),
        ),
        migrations.AddIndex(
            model_name='hydrationlog',
            index=models.Index(fields=['user', '-logged_at'], name='hydration_l_user_id_7764e4_idx'),
        ),
        migrations.AddIndex(
            model_name='intakelog',
            index=models.Index(fields=['user', '-logged_at'], name='intake_logs_user_id_5188c4_idx'),
        ),
        migrations.AddIndex(
            model_name='intakelog',
            index=models.Index(fields=['user', 'logged_at'], name='intake_logs_user_id_e176e3_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritiongoals',
            index=models.Index(fields=['user'], name='nutrition_g_user_id_54c3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionprogress',
            index=models.Index(fields=['user', '-progress_date'], name='nutrition_p_user_id_797cc6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nutritionprogress',
            unique_together={('user', 'progress_date')},
        ),
    ]
