# Generated by Django 5.2.8 on 2026-02-08 06:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=500)),
                ('address', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gyms',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('FULL_BODY', 'Full Body'), ('ARMS', 'Arms'), ('LEGS', 'Legs'), ('CORE', 'Core'), ('CARDIO', 'Cardio'), ('UPPER_BODY', 'Upper Body'), ('LOWER_BODY', 'Lower Body')], max_length=20)),
                ('estimated_duration', models.IntegerField(help_text='Estimated duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_workouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('FULL_BODY', 'Full Body'), ('ARMS', 'Arms'), ('LEGS', 'Legs'), ('CORE', 'Core'), ('CARDIO', 'Cardio'), ('UPPER_BODY', 'Upper Body'), ('LOWER_BODY', 'Lower Body')], max_length=20)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('calories_per_minute', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomWorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('sets', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('reps', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_seconds', models.IntegerField(default=0, help_text='Duration for time-based exercises', validators=[django.core.validators.MinValueValidator(0)])),
                ('rest_seconds', models.IntegerField(default=60, help_text='Rest time between sets', validators=[django.core.validators.MinValueValidator(0)])),
                ('custom_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.customworkout')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
            ],
            options={
                'db_table': 'custom_workout_exercises',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='customworkout',
            name='exercises',
            field=models.ManyToManyField(through='workouts.CustomWorkoutExercise', to='workouts.exercise'),
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=255)),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('calories_burned', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='workouts.customworkout')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_logs', to='workouts.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_logs',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('MAX_WEIGHT', 'Maximum Weight'), ('MAX_REPS', 'Maximum Reps'), ('MAX_DURATION', 'Maximum Duration'), ('FASTEST_TIME', 'Fastest Time')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('unit', models.CharField(help_text='kg, reps, seconds, etc.', max_length=20)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
                ('workout_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_records', to='workouts.workoutlog')),
            ],
            options={
                'db_table': 'personal_records',
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLogExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('workout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutlog')),
            ],
            options={
                'db_table': 'workout_log_exercises',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reps', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Duration for time-based exercises', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed', models.BooleanField(default=True)),
                ('workout_log_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workoutlogexercise')),
            ],
            options={
                'db_table': 'workout_sets',
                'ordering': ['set_number'],
            },
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['category'], name='exercises_categor_de47b7_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['difficulty'], name='exercises_difficu_bf8baf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customworkoutexercise',
            unique_together={('custom_workout', 'exercise', 'order')},
        ),
        migrations.AddIndex(
            model_name='workoutlog',
            index=models.Index(fields=['user', '-logged_at'], name='workout_log_user_id_a3af6b_idx'),
        ),
        migrations.AddIndex(
            model_name='personalrecord',
            index=models.Index(fields=['user', 'exercise', 'record_type'], name='personal_re_user_id_644f10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personalrecord',
            unique_together={('user', 'exercise', 'record_type')},
        ),
        migrations.AlterUniqueTogether(
            name='workoutset',
            unique_together={('workout_log_exercise', 'set_number')},
        ),
    ]
