# Generated by Django 5.2.8 on 2026-02-14 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('FREE_WEIGHTS', 'Free Weights'), ('MACHINES', 'Machines'), ('BODYWEIGHT', 'Bodyweight'), ('RESISTANCE_BANDS', 'Resistance Bands'), ('CARDIO_EQUIPMENT', 'Cardio Equipment')], default='BODYWEIGHT', max_length=50),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('LEGS', 'Legs'), ('CORE', 'Core'), ('ARMS', 'Arms'), ('SHOULDERS', 'Shoulders'), ('FULL_BODY', 'Full Body')], default='FULL_BODY', max_length=50),
        ),
        migrations.AlterField(
            model_name='customworkout',
            name='category',
            field=models.CharField(choices=[('STRENGTH', 'Strength'), ('CARDIO', 'Cardio'), ('BODYWEIGHT', 'Bodyweight'), ('MIXED', 'Mixed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('STRENGTH', 'Strength'), ('CARDIO', 'Cardio'), ('BODYWEIGHT', 'Bodyweight')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['muscle_group'], name='exercises_muscle__f519d0_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['equipment'], name='exercises_equipme_0bc618_idx'),
        ),
    ]
