# Generated by Django 5.2.8 on 2026-02-15 17:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_exercise_unique_exercise_name_case_insensitive'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('reps', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1000)])),
                ('order', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('workout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.workoutlog')),
            ],
            options={
                'db_table': 'workout_exercises',
                'ordering': ['order'],
            },
        ),
    ]
