# Generated by Django 5.2.8 on 2026-02-18 18:29

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_enhance_personalrecord_model'),
    ]

    operations = [
        # Add created_at with a default value for existing rows
        migrations.AddField(
            model_name='personalrecord',
            name='created_at',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        # Add updated_at with a default value for existing rows
        migrations.AddField(
            model_name='personalrecord',
            name='updated_at',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        # Now alter the fields to use auto_now_add and auto_now
        migrations.AlterField(
            model_name='personalrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
