# Generated by Django 5.2.8 on 2026-02-19 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_add_timestamps_to_personalrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add index on WorkoutLog.user_id (already exists as part of FK, but explicit for clarity)
        # Add index on WorkoutLog.date (logged_at field)
        migrations.AddIndex(
            model_name='workoutlog',
            index=models.Index(fields=['logged_at'], name='workouts_wo_logged__idx'),
        ),
        # Add composite index for common queries (user + date)
        migrations.AddIndex(
            model_name='workoutlog',
            index=models.Index(fields=['user', 'logged_at'], name='workouts_wo_user_lo_idx'),
        ),
        # Add index on PersonalRecord.user_id (already exists as part of FK, but explicit for clarity)
        # Add composite index for PersonalRecord queries (user + exercise)
        migrations.AddIndex(
            model_name='personalrecord',
            index=models.Index(fields=['user', 'exercise'], name='workouts_pe_user_ex_idx'),
        ),
        # Add index on PersonalRecord.achieved_date for sorting
        migrations.AddIndex(
            model_name='personalrecord',
            index=models.Index(fields=['-achieved_date'], name='workouts_pe_achieve_idx'),
        ),
        # Add composite index for WorkoutExercise queries (workout_log + order)
        migrations.AddIndex(
            model_name='workoutexercise',
            index=models.Index(fields=['workout_log', 'order'], name='workouts_wo_workout_idx'),
        ),
    ]
