# Generated by Django 5.2.8 on 2026-03-28 07:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_auditlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('angle_data', models.JSONField(default=dict, help_text='Joint angles at the time of rep detection')),
            ],
            options={
                'db_table': 'rep_events',
                'ordering': ['rep_number'],
            },
        ),
        migrations.CreateModel(
            name='RepSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('PUSH_UP', 'Push-ups'), ('SQUAT', 'Squats'), ('PULL_UP', 'Pull-ups'), ('BICEP_CURL', 'Bicep Curls'), ('SHOULDER_PRESS', 'Shoulder Press'), ('LUNGE', 'Lunges'), ('SIT_UP', 'Sit-ups')], max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_reps', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('confidence_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_converted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rep_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.RemoveIndex(
            model_name='personalrecord',
            name='personal_re_user_id_644f10_idx',
        ),
        migrations.AddField(
            model_name='repsession',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rep_sessions', to='workouts.exercise'),
        ),
        migrations.AddField(
            model_name='repsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repsession',
            name='workout_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rep_sessions', to='workouts.workoutlog'),
        ),
        migrations.AddField(
            model_name='repevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_events', to='workouts.repsession'),
        ),
        migrations.AddIndex(
            model_name='repsession',
            index=models.Index(fields=['user', '-start_time'], name='rep_session_user_id_975df0_idx'),
        ),
        migrations.AddIndex(
            model_name='repsession',
            index=models.Index(fields=['is_converted'], name='rep_session_is_conv_a0abe4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repevent',
            unique_together={('session', 'rep_number')},
        ),
    ]
