# Generated by Django 5.2.8 on 2026-04-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_repevent_repsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repsession',
            name='exercise_type',
            field=models.CharField(choices=[('PUSH_UP', 'Push-ups'), ('SQUAT', 'Squats'), ('PULL_UP', 'Pull-ups'), ('BICEP_CURL', 'Bicep Curls'), ('SHOULDER_PRESS', 'Shoulder Press'), ('LUNGE', 'Lunges'), ('SIT_UP', 'Sit-ups'), ('BENCH_DIP', 'Bench Dips')], max_length=20),
        ),
    ]
