# Generated by Django 5.2.8 on 2026-03-29 18:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('general', 'General'), ('getting_started', 'Getting Started'), ('nutrition', 'Nutrition Tracking'), ('workout', 'Workout Tracking'), ('challenges', 'Challenges')], max_length=50)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'faqs',
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
    ]
