# Generated by Django 5.2.8 on 2026-03-29 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.IntegerField(default=5000)),
                ('search_query', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gym_searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteGym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_gyms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_gyms',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'place_id')},
            },
        ),
    ]
